#! /bin/sh

${SNAP}/meta/hooks/plugs-helper serial-port

if [ $? -eq 1 ]; then
    # other interface must be connected
    exit 0
fi

# now we can start the service
if snapctl services ${SNAP_NAME}.${SNAP_NAME} | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.${SNAP_NAME} 2>&1 || true
fi

