name: turtlebot4-desktop
version: '0.1'
summary: Turtlebot4 desktop.
description: |
  Turtlebot4 desktop.

grade: devel
confinement: strict
base: core20

package-repositories:
- components: [main]
  formats: [deb]
  key-id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  key-server: keyserver.ubuntu.com
  suites: [focal]
  type: apt
  url: http://repo.ros2.org/ubuntu/main

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  ros2-galactic-extension:
    build-packages: [ros-galactic-ros-core]
    override-build: install -D -m 0755 launch ${SNAPCRAFT_PART_INSTALL}/snap/command-chain/ros2-launch
    plugin: nil
    source: $SNAPCRAFT_EXTENSIONS_DIR/ros2

  turtlebot4-desktop:
    after: [ros2-galactic-extension, desktop-qt5]
    plugin: colcon
    source: .
    colcon-catkin-cmake-args: ["-DCMAKE_BUILD_TYPE=Release"]
    build-packages: [git, python3-vcstool]
    stage-packages: [ros-galactic-ros2launch, ros-galactic-ros2run]
    override-pull: |
            snapcraftctl pull
            vcs import < tb4.repositories
            vcs import < turtlebot4/dependencies.repos
            vcs import < tb4_desktop.repositories
    build-environment:
    - ROS_VERSION: '2'
    - ROS_DISTRO: galactic

apps:
  view-robot:
    command: bin/desktop-launch $SNAP/opt/ros/galactic/bin/ros2 launch turtlebot4_viz view_robot.launch.py
    plugs: [network, network-bind, desktop, desktop-legacy, x11, opengl, home]
    command-chain: [snap/command-chain/ros2-launch]
    environment:
      PYTHONPATH: $SNAP/opt/ros/galactic/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages:${PYTHONPATH}
      ROS_DISTRO: galactic
      ROS_VERSION: '2'
  rviz2:
    command: bin/desktop-launch $SNAP/opt/ros/galactic/bin/ros2 run rviz2 rviz2
    plugs: [network, network-bind, desktop, desktop-legacy, x11, opengl, home]
    command-chain: [snap/command-chain/ros2-launch]
    environment:
      PYTHONPATH: $SNAP/opt/ros/galactic/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages:${PYTHONPATH}
      ROS_DISTRO: galactic
      ROS_VERSION: '2'
      QT_QPA_PLATFORMTHEME: gtk3
